version: "3.8"

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-config/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Change if needed
      - GF_SECURITY_ADMIN_PASSWORD=admin # Change for security
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning

volumes:
  grafana-data:
